apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-consumer
spec:
  replicas: 5
  selector:
    matchLabels:
      app: redis-consumer
  template:
    metadata:
      labels:
        app: redis-consumer
    spec:
      hostNetwork: true
      containers:
        - name: redis-consumer
          image: scottzach1/redis-consumer
