# THIS IS A NON_FUNCTIONAL DRAFT!!
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-scaledobject
  labels:
    deploymentName: redis-consumer
spec:
  maxReplicaCount: 4
  pollingInterval: 3  # Optional. Default: 30 seconds
  cooldownPeriod:  5  # Optional. Default: 300 seconds
  scaleTargetRef:
    name: redis-consumer
  triggers:
    - type: redis  # https://keda.sh/docs/2.7/scalers/redis-lists/
      metadata:
        usernameFromEnv: REDIS_USERNAME # optional
        passwordFromEnv: REDIS_PASSWORD
        listName: mylist # Required
        listLength: "5" # Required
        enableTLS: "false" # optional
        databaseIndex: "0" # optional
        # Alternatively, you can use existing environment variables to read configuration from:
        # See details in "Parameter list" section
        addressFromEnv: REDIS_HOST # Optional. You can use this instead of `address` parameter
